name: 'InferSharp'
description: 'Scalable and interprocedural C# code analyzer for detecting race condition, null pointer derefs and resource leaks'
branding:
  icon: 'search'
inputs:
  binary-path:
    description: 'The path where the binaries (.dll and .pdb) are located.'
    required: true
    default: '.'
  optional-flags:
    description: 'Optional flags, see https://fbinfer.com/docs/man-infer-run/#OPTIONS for the complete list.'
    required: false
outputs:
  results:
    description: 'The analysis results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.binary-path }}
    - ${{ inputs.optional-flags }}
